/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author auada
 */
public class Voo2 extends javax.swing.JFrame {

    /**
     * Creates new form Voo2
     */
    public Voo2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltar2_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        assento2_txt = new javax.swing.JTextField();
        reserva2_btn = new javax.swing.JButton();
        msg2_lbl = new javax.swing.JLabel();
        assento1v2_lbl = new javax.swing.JLabel();
        assento2v2_lbl = new javax.swing.JLabel();
        assento3v2_lbl = new javax.swing.JLabel();
        assento4v2_lbl = new javax.swing.JLabel();
        assento5v2_lbl = new javax.swing.JLabel();
        assento6v2_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(196, 230, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));

        voltar2_btn.setText("voltar");
        voltar2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar2_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("assentos");

        jLabel2.setText("vôo 33145");

        assento2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assento2_txtActionPerformed(evt);
            }
        });

        reserva2_btn.setText("reservar");
        reserva2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserva2_btnActionPerformed(evt);
            }
        });

        assento1v2_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assento1v2_lbl.setText("1 [ x ]");

        assento2v2_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assento2v2_lbl.setText("2 [   ]");

        assento3v2_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assento3v2_lbl.setText("3 [   ]");

        assento4v2_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assento4v2_lbl.setText("4 [ x ]");

        assento5v2_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assento5v2_lbl.setText("5 [ x ]");

        assento6v2_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assento6v2_lbl.setText("6 [ x ]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136)
                        .addComponent(voltar2_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(assento2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reserva2_btn)
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(msg2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(assento5v2_lbl)
                    .addComponent(assento3v2_lbl)
                    .addComponent(assento1v2_lbl))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(assento2v2_lbl)
                    .addComponent(assento4v2_lbl)
                    .addComponent(assento6v2_lbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar2_btn)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assento1v2_lbl)
                    .addComponent(assento2v2_lbl))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assento3v2_lbl)
                    .addComponent(assento4v2_lbl))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assento5v2_lbl)
                    .addComponent(assento6v2_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(msg2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assento2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserva2_btn))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltar2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar2_btnActionPerformed
        dispose();
            new Inicio_GUI().setVisible(true);
    }//GEN-LAST:event_voltar2_btnActionPerformed

    private void assento2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assento2_txtActionPerformed

    }//GEN-LAST:event_assento2_txtActionPerformed

    private void reserva2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserva2_btnActionPerformed
        Model.Funcoes_DAO.assentolivre2();
    }//GEN-LAST:event_reserva2_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel assento1v2_lbl;
    public static javax.swing.JTextField assento2_txt;
    public static javax.swing.JLabel assento2v2_lbl;
    public static javax.swing.JLabel assento3v2_lbl;
    public static javax.swing.JLabel assento4v2_lbl;
    public static javax.swing.JLabel assento5v2_lbl;
    public static javax.swing.JLabel assento6v2_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel msg2_lbl;
    private javax.swing.JButton reserva2_btn;
    private javax.swing.JButton voltar2_btn;
    // End of variables declaration//GEN-END:variables
}
